name: Spotify Recently Played

on:
  schedule:
    - cron: '0 */1 * * *' # Roda automaticamente a cada 1 hora
  workflow_dispatch: # Permite rodar manualmente quando quiser

jobs:
  update-readme:
    name: Update Readme with Spotify
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: kittinan/spotify-github-profile@master
        with:
          spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          spotify_client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          spotify_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
